# Generated by Django 6.0.1 on 2026-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('HOODIE', 'Hoodie'), ('JACKET', 'Jacket'), ('SHIRT', 'Shirt'), ('PANT', 'Pant')], default='HOODIE', max_length=20),
        ),
    ]
